### ISSUE TITLE
CLiond doesn't read the .gdbinit from the project root

### ISSUE THREAD

**Issue by nagelkl** [nagelkl/clion_embedded#4]
At the moment the gdbserver configuration of CLion reads the .gdbinit from %HOMEPATH%

**Comment by nagelkl** [comment]
Since there is no local .gdbinit in the project root starting the debugger via command line leads to a partially configered debug session with no binary loaded to the target.

**Comment by philsquared** [comment]
This is quite old, but CLion has supported reading .gdbinit from the project root since 2019.3, now. If you're still maintaining this project is it worth looking at this again?

**Comment by nagelkl** [comment]
Changed the Run / Debug- Type, now no .gdbinit file is neccessary any more.  Also a build befor debug is possible.

see c150d862249a7157739decea60eb5b7e6ce3a9ac for details
